#!/bin/bash
# created by Lukas Balonek (lukas.balonek@gmail.com)
bh=/dev/null
MOUNTPOINT=/tmp/rpi-image-build
IMGSIZE=4096
CPU_CORES=$(grep -c '^processor' /proc/cpuinfo)
APT_PREREQS="binfmt-support qemu-user-static debootstrap dosfstools xz-utils fdisk coreutils sed"

set -e

function separathor {
        echo -e "\e[09m                                                            \e[m"
}

function error {
        echo -e "\e[31m$error_msg Quitting...\e[m"
        exit 1
}

function check_root {
        if ! [ $(id -u) -eq 0 ]; then
                error_msg="You have to execute imageathor as root/sudo !"
                error
        fi
}

function help {

        separathor
        echo -e "\e[1mRPi image generathor\e[m"
        echo "This script creates image for raspberry pi sd card with specified architecture"
        echo
        echo -e "\e[1mUsage:\e[m sudo rpi-image-generathor [args]"
        echo
        echo -e "\e[1mArgs:\e[m"
        echo "[--arch=(armel|armhf|arm64)]"
        echo "[--imgname=<name of your image>]"
        echo "[--folder=<path where image should be stored>]"
        echo
        echo -e "\e[1mWithout args specified, armel, rpi-image-\$arch.img and PWD are used.\e[m"
        echo
        echo -e "\e[1mExamples:\e[m"
        echo -e "Make basic armel raspberry image"
        echo -e "\e[3msudo rpi-image-generathor --arch=armel\e[m"
        echo
        echo -e "Make basic arm64 raspberry image"
        echo -e "\e[3msudo rpi-image-generathor --arch=arm64\e[m"
        echo
        echo -e "Make basic armhf raspberry image with name rpi3-image.img"
        echo -e "\e[3msudo rpi-image-generathor --arch=armhf --imgname=rpi3-image.img\e[m"
        exit 0
        separathor

}

function check_folder_writability {
        if [ -n "$backup_folder" ]; then
                if ! [ -w "$(dirname $backup_folder)" ]; then
                        error_msg="Folder $backup_folder is not writable !"
                        error
                fi
        fi
}

function lineinfile {
        # first arg is regexp, second line, third is file
        grep -qE $1 $3 || declare -i exit_value=1
        if [ $exit_value -eq 1 ]; then
                printf $2 >> $3
        else
                sed -i "s/$1/$2/g" $3
        fi
}

#################### START ####################

for arg in $@; do

        case $arg in
                --arch=*)
                arch=$(echo $arg | cut -d "=" -f2)
                if ! ([ $arch == armel ] || [ $arch == armhf ] || [ $arch == arm64 ]); then
                        error_msg="Wrong architecture specified !"
                        error
                fi
                ;;
                --imgname=*)
                imgname=$(echo $arg | cut -d "=" -f2)
                ;;
                --folder=*)
                folder=$(echo $arg | cut -d "=" -f2)
                ;;
                --help) help
                ;;
                *) error_msg="Wrong parameter specified ! \e[mUse \e[1mrpi-image-generathor --help\e[m to get usage info."; error
                ;;
        esac
done

check_root
check_folder_writability

separathor
echo -e " \e[92mWelcome to rpi-image-generathor ! \e[m"
separathor

if [ -z $arch ]; then
        arch=armel
        echo -e "\e[33mNo arch specified, setting to armel (RPi 1) \e[m"
fi

if [ -z $imgname ]; then
        imgname=rpi-image-$arch.img
        echo -e "\e[33mNo imgname specified, setting to $imgname \e[m"
fi

if [ -f $imgname ]; then
        error_msg="Image $imgname already exist, not overwriting !"
        error
fi

if [ -z $folder ]; then
        folder=$PWD
        echo -e "\e[33mNo folder specified, setting to $folder \e[m"
fi

echo -e "\e[33mInstalling prerequisites\e[m"
apt -yqq install $APT_PREREQS

echo -e "\e[33mRegistering arm architecture in binfmt\e[m"
set +e
echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' > /proc/sys/fs/binfmt_misc/register
set -e

echo -e "\e[33mCreating blank image\e[m"
dd if=/dev/zero bs=1M count=$IMGSIZE status=progress of=$imgname

echo -e "\e[33mConnecting image to loop device\e[m"
losetup --partscan --find $imgname
disk_device=$(losetup --list | grep $imgname | awk '{print $1}')
echo "Disk device is: $disk_device"

echo -e "\e[33mFormatting $disk_device\e[m"
fdisk 1>$bh $disk_device << EOF
o
n
p
1

+100M
t
c
n
p
2


w
EOF

mkfs.vfat -F 32 "$disk_device"p1
mkfs.ext4 -F "$disk_device"p2

echo -e "\e[33mConnecting partitions\e[m"
mkdir -p $MOUNTPOINT
mount -v "$disk_device"p2 $MOUNTPOINT
mkdir -p $MOUNTPOINT/boot/firmware
mount -v "$disk_device"p1 $MOUNTPOINT/boot/firmware

echo -e "\e[33mInstalling system with debootstrap - STAGE 1\e[m"
debootstrap --variant=minbase --foreign --arch $arch stable $MOUNTPOINT http://deb.debian.org/debian

echo -e "\e[33mCopying qemu-arm-static into $MOUNTPOINT/usr/bin to make chroot possible\e[m"
cp -fv $(which qemu-arm-static) $MOUNTPOINT/usr/bin/

echo -e "\e[33mInstalling system with debootstrap - STAGE 2\e[m"
mount -v --bind /proc $MOUNTPOINT/proc
mount -v --bind /sys $MOUNTPOINT/sys
chroot $MOUNTPOINT /debootstrap/debootstrap --second-stage

echo -e "\e[33mSetting APT\e[m"
echo deb http://deb.debian.org/debian stable main contrib non-free > $MOUNTPOINT/etc/apt/sources.list
chroot $MOUNTPOINT apt -yqq update

echo -e "\e[33mInstalling linux-image for $arch\e[m"
case $arch in
armel)
pkg_name=linux-image-rpi
# linux-image-rpi - Linux for Raspberry Pi and Pi Zero
;;
armhf)
pkg_name=linux-image-armmp
# linux-image-armmp - Linux for ARMv7 multiplatform compatible SoCs
;;
arm64)
pkg_name=linux-image-arm64
# linux-image-arm64 - Linux for 64-bit ARMv8 machines
;;
esac
chroot $MOUNTPOINT /bin/bash -c "declare -x DEBIAN_FRONTEND=noninteractive; apt install -yqq $pkg_name"

echo -e "\e[33mInstalling important packages\e[m"
chroot $MOUNTPOINT /bin/bash -c "
  declare -x DEBIAN_FRONTEND=noninteractive; \
  apt install -yq locales `# GNU C Library: National Language (locale) data [support]` \
  init `# init system` \
  openssh-server `# secure shell (SSH) server, for secure access from remote machines` \
  raspi-firmware `# Raspberry Pi family GPU firmware and bootloaders` \
  systemd-timesyncd `# minimalistic service to synchronize local time with NTP servers` \
  cron `# process scheduling daemon` \
  iproute2 `# networking and traffic control tools` \
  ifupdown `# high level tools to configure network interfaces` \
  fdisk `# collection of partitioning utilities`
"

echo -e "\e[33mInstalling must-have packages\e[m"
chroot $MOUNTPOINT /bin/bash -c "
  declare -x DEBIAN_FRONTEND=noninteractive; \
  apt install -yq locales `# GNU C Library: National Language (locale) data [support]` \
  htop iftop iotop nload `# monitoring tools` \
  tree mc `# file manager tools` \
  nano `# small, friendly text editor inspired by Pico` \
  e2fsprogs `# ext2/ext3/ext4 file system utilities` \
  cloud-guest-utils `# It contains growpart for resizing a partition during boot`
"

echo -e "\e[33mSetting locales\e[m"
echo LANGUAGE=en_US:en > $MOUNTPOINT/etc/default/locale
echo LANG=en_US.UTF-8 >> $MOUNTPOINT/etc/default/locale
echo LC=en_US.UTF-8 >> $MOUNTPOINT/etc/default/locale
sed -i 's@.*# cs_CZ.UTF-8 UTF-8@cs_CZ.UTF-8 UTF-8@g' $MOUNTPOINT/etc/locale.gen
sed -i 's@.*# en_US.UTF-8 UTF-8@en_US.UTF-8 UTF-8@g' $MOUNTPOINT/etc/locale.gen
chroot $MOUNTPOINT locale-gen

echo -e "\e[33mSetting hostname\e[m"
echo raspberry > $MOUNTPOINT/etc/hostname

echo -e "\e[33mSetting fstab\e[m"
cat > $MOUNTPOINT/etc/fstab << EOF
/dev/mmcblk0p1 /boot/firmware vfat defaults 0 0
/dev/mmcblk0p2 / ext4 defaults 0 0
EOF

echo -e "\e[33mSetting accounts\e[m"
echo "Adding user pi with password malina"
chroot $MOUNTPOINT /bin/bash -c "useradd -s /bin/bash --user-group --create-home pi"
chroot $MOUNTPOINT /bin/bash -c "echo 'pi:malina' | chpasswd" ;
echo "Setting root password to linux"
chroot $MOUNTPOINT /bin/bash -c "echo 'root:linux' | chpasswd" ;

echo -e "\e[33mSetting sshd\e[m"
mkdir -p $MOUNTPOINT/root/.ssh
sed -i 's/^.*PermitRootLogin.*/PermitRootLogin yes/g' $MOUNTPOINT/etc/ssh/sshd_config

echo -e "\e[33mSetting network\e[m"
echo "Disable IPv6"
echo 'net.ipv6.conf.eth0.disable_ipv6 = 1' > $MOUNTPOINT/etc/sysctl.d/99-disable-ipv6.conf
echo "Set eth0 interface"
cat > $MOUNTPOINT/etc/network/interfaces.d/eth0 << EOF
auto eth0
iface eth0 inet dhcp
EOF

echo -e "\e[33mSetting time (Prague - CZ timezone, NTP)\e[m"
ln -snfr $MOUNTPOINT/usr/share/zoneinfo/Europe/Prague $MOUNTPOINT/etc/localtime
cat > $MOUNTPOINT/etc/systemd/timesyncd.conf << EOF
[Time]
NTP=tik.cesnet.cz tak.cesnet.cz time.windows.com ntp.nic.cz europe.pool.ntp.org
FallbackNTP=0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org
PollIntervalMaxSec=1800
PollIntervalMinSec=60
EOF
chroot $MOUNTPOINT /bin/bash -c "systemctl unmask systemd-timesyncd ; systemctl enable systemd-timesyncd"

echo -e "\e[33mSetting crontab\e[m"
touch $MOUNTPOINT/var/spool/cron/crontabs/root
chmod 0600 $MOUNTPOINT/var/spool/cron/crontabs/root

echo -e "\e[33mSetting console message (/etc/issue)\e[m"
cat > $MOUNTPOINT/etc/issue << EOF
OS: \S (\l)
Hostname: \n
IPv4: \4
EOF

echo -e "\e[33mSetting Read-Only OverlayFS\e[m"
echo "Adding overlay module into initramfs-tools/modules"
lineinfile ^overlay.* overlay $MOUNTPOINT/etc/initramfs-tools/modules

echo "Disable OverlayFS by default (/boot/overlay.txt)"
echo 0 > $MOUNTPOINT/boot/overlay.txt
echo "Adding post-<update-initramfs> script"
cat > $MOUNTPOINT/usr/local/sbin/update-initramfs-overlay << EOF
#!/bin/bash
set -e

# update-initramfs
/usr/sbin/update-initramfs -u

# if youre generating/updating initramfs on overlay /, it will set root=overlay
# in cmdline.txt and system wont survive reboot
rootfs_device=$(grep " / " /etc/fstab | cut -d " " -f1)
sed -i "s\ root=overlay \ root=\$rootfs_device \g" /boot/firmware/cmdline.txt
EOF
chmod +x $MOUNTPOINT/usr/local/sbin/update-initramfs-overlay

echo "Adding initramfs 01-overlay init-bottom script"
cat > $MOUNTPOINT/etc/initramfs-tools/scripts/init-bottom/01-overlay << EOF
set -e
PREREQ=""
prereqs(){
   echo "${PREREQ}"
}
case "${1}" in
   prereqs)
      prereqs
      exit 0
      ;;
esac

echo
if [ \$(cat \${rootmnt}/boot/overlay.txt) -eq 1 ]; then

echo -e "[overlay] Image is in Read-Only, executing overlayfs"

        echo -e "[overlay] Creating dir /sysroot to move rootfs mount here"
        mkdir -p /sysroot

        echo -e "[overlay] Moving rootfs mount to /sysroot"
        mount -v -o move \${rootmnt} /sysroot

        echo -e "[overlay] Creating directories for overlay ramdisk"
        /bin/mkdir -p /write

        echo -e "[overlay] Mounting tmpfs as overlay upper&work dir"
        /bin/mount -t tmpfs tmpfs /write

        echo -e "[overlay] Creating folders upper&work"
        mkdir -p /write/rw /write/work

        echo -e "[overlay] Mounting overlayFS"
        mount -t overlay overlay -o lowerdir=/sysroot,upperdir=/write/rw,workdir=/write/work /root

else

echo -e "[overlay] Image is in Read-Write, booting from ${root} mounted on ${rootmnt}"

fi
EOF
chmod +x $MOUNTPOINT/etc/initramfs-tools/scripts/init-bottom/01-overlay

echo -e "\e[33mUpdating initramfs\e[m"
chroot $MOUNTPOINT update-initramfs-overlay

echo -e "\e[33mDisconnecting partitions\e[m"
umount -v $MOUNTPOINT/boot/firmware
umount -v $MOUNTPOINT

echo -e "\e[33mDisconnecting image from loop device\e[m"
losetup -d $disk_device

echo -e "\e[33mCompressing image with xz\e[m"
xz --compress -9 --threads=$CPU_CORES $imgname

echo -e "\e[33mRemoving build folders\e[m"
mount | grep $MOUNTPOINT && declare -i exit_value=0 || declare -i exit_value=1
if [ $exit_value -eq 0 ]; then
        error_msg="Something failed to unmount ! Not removing build folders: $MOUNTPOINT"
        error
else
        rm -rfv rpi-image-build
fi

if [ "$PWD/"$imgname".xz" == "$folder/"$imgname".xz" ]; then
  echo -e "\e[32mImage is already in destination dir...\e[m"
else
mv -fv "$imgname".xz $folder/"$imgname".xz
fi

echo -e "\e[32mCompleted ! Image can be found here: $folder/$imgname".xz"\e[m"
